#!/bin/sh

# ---------------
# List & Navigate
# ---------------
alias ll="ls -lhaFp"          # Better 'ls'
alias lr="ls -lhaFpR"         # List recursively
alias lf="ll | grep ^[-l]"    # List files only
alias ld="ll | grep ^d"       # List directories only

alias cd.="cd ../"                                # Go back 1 directory level
alias cd..="cd ../../"                            # Go back 2 directory levels
alias cd...="cd ../../../"                        # Go back 3 directory levels

# --------
# Homebrew
# --------
if [ -f `brew --prefix`/etc/bash_completion ]; then
  . `brew --prefix`/etc/bash_completion
fi

alias lbrew="brew list --versions"       # List installed brew packages
alias cbrew="lcd /usr/local/Cellar"      # Go & list brew folder

# ---
# Npm
# ---
alias lnpm="npm list -g --depth=0"       # List installed npm packages

# ----
# Misc
# ----
alias cp="cp -iv"                                 # Better 'cp'
alias cpath="echo -e ${PATH//:/\\n}"              # Echo env paths
alias less="less -FSRXc"                          # Better 'less'
alias mkd="mkdir -pv"                             # Better 'mkdir'
alias mv="mv -iv"                                 # Better 'mv'
alias grep="grep --color=auto"                    # Better 'grep'
alias sprofile="source $USER_HOME/.bash_profile"  # Source profile
alias qfind="sudo find . -name "                  # Quick find file
alias qfindpattern="sudo grep -rnw '.' -e "       # Quick find pattern in files from current directory
alias finder="open -a Finder ./"                  # Opens current directory in Finder
alias top="top -R -F -s 10 -o rsize"              # Recommended 'top' invocation to minimize resources
alias lnet='lsof -i'                              # Show all open TCP/IP sockets
